version: "3.9"

services:
  app:
    build: .
    container_name: flight_app_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flight_app_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: myPass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgress_db
    restart: always
    environment:
      POSTGRES_DB: flight_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network: